/*
 * Waiting List Api
 *
 * Ambulance Waiting List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: mail@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

import (
	"github.com/gin-gonic/gin"
)

type AmbulanceWaitingListAPI struct {
}

// Get /api/waiting-list/:ambulanceId/entries
// Provides the ambulance waiting list 
func (api *AmbulanceWaitingListAPI) GetWaitingListEntries(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

