/*
 * Waiting List Api
 *
 * Ambulance Waiting List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: mail@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

import (
   "net/http"

   "github.com/gin-gonic/gin"
)

type AmbulanceWaitingListAPI interface {

   // internal registration of api routes
   addRoutes(routerGroup *gin.RouterGroup)

    // GetWaitingListEntries - Provides the ambulance waiting list
   GetWaitingListEntries(ctx *gin.Context)

}

// partial implementation of AmbulanceWaitingListAPI - all functions must be implemented in add on files
type implAmbulanceWaitingListAPI struct {

}

func newAmbulanceWaitingListAPI() AmbulanceWaitingListAPI {
  return &implAmbulanceWaitingListAPI{}
}

func (this *implAmbulanceWaitingListAPI) addRoutes(routerGroup *gin.RouterGroup) {
  routerGroup.Handle( http.MethodGet, "/waiting-list/:ambulanceId/entries", this.GetWaitingListEntries)
}

// Copy following section to separate file, uncomment, and implement accordingly
// // GetWaitingListEntries - Provides the ambulance waiting list
// func (this *implAmbulanceWaitingListAPI) GetWaitingListEntries(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//

